./cub3d maps/ok_info_order.cub
./cub3d maps/ok_color_space.cub
./cub3d maps/ok_map.cub
./cub3d maps/ok_map1.cub
./cub3d maps/ok_map2.cub
./cub3d maps/ok_map3.cub
./cub3d maps/ok_map4.cub
./cub3d maps/ok_minimal.cub
./cub3d maps/ok_new_lines.cub
./cub3d maps/ok_offset_wall.cub
./cub3d maps/ok_offset_wall2.cub
./cub3d maps/ok_one_elem_first_line1.cub
./cub3d maps/ok_one_elem_first_line2.cub
./cub3d maps/ok_simple.cub
./cub3d maps/ok_spaces_in_element.cub
./cub3d maps/ok_strange.cub