./cub3d maps/ko_color_format.cub
./cub3d maps/ko_color_format1.cub
./cub3d maps/ko_color_format2.cub
./cub3d maps/ko_color_missing.cub
./cub3d maps/ko_color_neg.cub
./cub3d maps/ko_color_non_digit.cub
./cub3d maps/ko_color_over_255.cub
./cub3d maps/ko_color_typo.cub
./cub3d maps/ko_element_order.cub
./cub3d maps/ko_empty.cub
./cub3d maps/ko_invalid_texture.cub
./cub3d maps/ko_map_missing.cub
./cub3d maps/ko_map_missing.cub:Zone.Identifier
./cub3d maps/ko_missing_ext
./cub3d maps/ko_missing_space.cub
./cub3d maps/ko_missing_space2.cub
./cub3d maps/ko_missing_wall.cub
./cub3d maps/ko_missing_wall2.cub
./cub3d maps/ko_missing_wall3.cub
./cub3d maps/ko_more_info_than_necessary_info.cub
./cub3d maps/ko_no_player.cub
./cub3d maps/ko_nonsense_map.cub
./cub3d maps/ko_open1.cub
./cub3d maps/ko_open2.cub
./cub3d maps/ko_open3.cub
./cub3d maps/ko_open4.cub
./cub3d maps/ko_open5.cub
./cub3d maps/ko_open6.cub
./cub3d maps/ko_open7.cub
./cub3d maps/ko_open8.cub
./cub3d maps/ko_open9.cub
./cub3d maps/ko_open10.cub
./cub3d maps/ko_player_in_walls.cub
./cub3d maps/ko_spaces_new_lines.cub
./cub3d maps/ko_spaces_text.cub
./cub3d maps/ko_spaces.cub
./cub3d maps/ko_texture_file_missing.cub
./cub3d maps/ko_texture_missing.cub
./cub3d maps/ko_texture_typo.cub
./cub3d maps/ko_wrong_char.cub
./cub3d maps/ko_wrong_ext.cub1
./cub3d maps/ko_only_wall.cub
./cub3d maps/ok_map.cub blabla
./cub3d maps