./cub3d maps/ok_info_order.cub
echo $?
./cub3d maps/ok_map1.cub
echo $?
./cub3d maps/ok_map2.cub
echo $?
./cub3d maps/ok_map3.cub
echo $?
./cub3d maps/ok_map4.cub
echo $?
./cub3d maps/ok_minimal.cub
echo $?
./cub3d maps/ok_new_lines.cub
echo $?
./cub3d maps/ok_offset_wall.cub
echo $?
./cub3d maps/ok_offset_wall2.cub
echo $?
./cub3d maps/ok_one_elem_first_line1.cub
echo $?
./cub3d maps/ok_one_elem_first_line2.cub
echo $?
./cub3d maps/ok_simple.cub
echo $?
./cub3d maps/ok_spaces_in_element.cub
echo $?
./cub3d maps/ok_strange.cub
echo $?